// <auto-generated />
using GF2Learn.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GF2Learn.Web.Data.Migrations
{
    [DbContext(typeof(Gf2LearnDbContext))]
    [Migration("20260818161246_HardenLearningGroupAccess")]
    partial class HardenLearningGroupAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            AddAdminActivityIndexes.BuildTargetModelCore(modelBuilder);

            modelBuilder.Entity("GF2Learn.Web.Models.LearningGroupAccessToken", b =>
            {
                b.HasIndex("GroupId")
                    .IsUnique()
                    .HasDatabaseName("UX_learning_group_access_tokens_active_join_code")
                    .HasFilter("\"Kind\" = 1 AND \"RevokedAt\" IS NULL");
            });
        }
    }
}
