using GF2Learn.Web.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GF2Learn.Web.Data.Migrations;

[DbContext(typeof(Gf2LearnDbContext))]
[Migration("20260607180000_AddExercisePartVerifications")]
public partial class AddExercisePartVerifications : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // This migration originally shipped without EF discovery metadata. Some
        // installations may therefore have had the table created manually while
        // lacking the migration-history row. Keep the repaired migration safe for
        // both those databases and a completely fresh installation.
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS exercise_part_verifications (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "UserSub" character varying(128) NOT NULL,
                "ContentSlug" character varying(128) NOT NULL,
                "PartIndex" integer NOT NULL,
                "IsSolved" boolean NOT NULL,
                "VerifiedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_exercise_part_verifications" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS
                "IX_exercise_part_verifications_UserSub_ContentSlug_PartIndex"
            ON exercise_part_verifications ("UserSub", "ContentSlug", "PartIndex");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "exercise_part_verifications");
    }
}
